version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 1433:5432

    environment:
      - POSTGRES_DB=TVISNS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=[ENTER YOUR PASSWORD]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080